name: Build and test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        py-version: ["py37", "py38", "py39", "py310", "py311"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ruff pytest pytest-mock pytest-cov tox bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run flake8
        run: |
          flake 8 --config=.flake8

      - name: Run pytest
        run: |
          pytest

      - name: Run tox
        run: tox

      - name: Run bandit
        run: |
          bandit -r src/clapy/
