name: Build and test

on: [push]

jobs:
  build:

    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        #python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.7"]
        #py-version: ["py37", "py38", "py39", "py310", "py311"]
        py-version: ["py37"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 pytest black isort pytest-mock pytest-cov mypy tox bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest
        run: |
          pytest -v -o "addopts=" --cov=src/clapy || true

      - name: Run tox
        run: tox || true

      - name: Run bandit
        run: |
          bandit -r src/clapy/ || true

      - name: Run linting and formatting checks
        run: |
          flake8 --config=.flake8 || true
          black --check .
          isort --check-only .
